data:
  block_size: 240
  duration: 2
  sampling_rate: 24000
  # f"/volume/wayne-nas-ai-music/vocoder/ddsp-revised/data/{"f1"|"m1"}/{f"train-"{"full"|"3min"}"|"val"|"test"]"
  train_path: /volume/wayne-nas-ai-music/vocoder/ddsp-revised/data/f1/train-full
  valid_path: /volume/wayne-nas-ai-music/vocoder/ddsp-revised/data/f1/val
model:
  num_wavetables: 20
  len_wavetables: 512
  is_lpf: true
loss:
  n_ffts: [1024, 512, 256, 128]
device: cuda
env:
  # exp/{"f1"|"m1"}-{"full"|"3min"}/dws-N20
  expdir: exp/f1-full/dws-N20
  gpu: 0
  gpu_id: 0
inference:
  batch_size: 1
train:
  batch_size: 16
  epochs: 100000
  interval_log: 10
  interval_save: 500
  interval_val: 500
  lr: 0.002
