data:
  block_size: 240
  duration: 2
  sampling_rate: 24000
  # f"/volume/wayne-nas-ai-music/vocoder/ddsp-revised/data/{"f1"|"m1"}/{f"train-"{"full"|"3min"}"|"val"|"test"]"
  train_path: /volume/wayne-nas-ai-music/vocoder/ddsp-revised/data/f1/train-full
  valid_path: /volume/wayne-nas-ai-music/vocoder/ddsp-revised/data/f1/val
model:
  n_mag_harmonic: 256
  n_mag_noise: 80
  n_harmonics: 150
loss:
  n_ffts: [1024, 512, 256, 128]
device: cuda
env:
  # exp/{"f1"|"m1"}-{"full"|"3min"}/full-256
  expdir: exp/f1-full/full-256
  gpu: 0
  gpu_id: 0
inference:
  batch_size: 1
train:
  batch_size: 16
  epochs: 100000
  interval_log: 10
  interval_save: 500
  interval_val: 500
  lr: 0.002
