data:
  block_size: 240
  duration: 2
  sampling_rate: 24000
  train_path: data/solo/train-full
  valid_path: data/solo/val
model:
  n_mag_harmonic: 256
  n_mag_noise: 80
  n_harmonics: 150
loss:
  n_ffts: [1024, 512, 256, 128]
device: cuda
env:
  expdir: exp/solo-full/full-256
  gpu: 0
  gpu_id: 0
inference:
  batch_size: 1
train:
  batch_size: 16
  epochs: 100000
  interval_log: 10
  interval_save: 500
  interval_val: 500
  lr: 0.002
